spring:
  application:
    name: pms-api-t1
  jpa:
    properties:
      hibernate.generate_statistics: false
      hibernate.globally_quoted_identifiers: true
      hibernate.metadata_builder_contributor: com.hyron.pms.common.core.UUIDMetadataBuilderContributor
      hibernate.jdbc.fetch_size: 50
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pms
    username: pms
    password: pms

  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 200MB

cloud:
  aws:
    region:
      static: ap-northeast-1
    credentials:
      access-key: dummy
      secret-key: dummy

client:
  url:
    root: http://localhost:8080

server:
  port: 8280
  max-http-header-size: 10KB
  forward-headers-strategy: framework
  tomcat:
    mbeanregistry:
      enabled: true
    max-http-form-post-size: 500MB

management:
  metrics:
    tags:
      actuator-metrics: pms-api-t1

tenant-filter:
  enable-repositories:
  exclude-tenants: XY
